### ISSUE TITLE
IndexError: Tuple index out of range

### ISSUE THREAD

**Issue by hanfu-bios** [seqcode/miniMDS#13]
I tried to run the package with human chromosome data from chromosome 1 to chromosome 22 with 1 Mb resolution. The data are formatted as below (count has been normalized):

chr7 133000001 134000000 chr12   5000001   6000000 0.00197448599730519

The files were names according to the instructions.

After identifying loci and reading data, an error occurred which said that 
```
in partitionedMDS
    alpha2 = args[6]
IndexError: tuple index out of range
```

Has anyone had any idea how to debug this?

Thanks a lot!

**Comment by Lila14** [comment]
I just tested the code with my data and didn't get an error. I've pushed the latest commits just to be sure. Can you attach your input file?

**Comment by hanfu-bios** [comment]
Yes, of course. Attached are the input files. I used the following command to run the code.

python ../miniMDS/minimds_inter.py -C 22 -n 5 -o K562res bulkA/K562 1000000 1000000 

Thank you!

[K562.zip](https://github.com/seqcode/miniMDS/files/2206231/K562.zip)

**Comment by Lila14** [comment]
There was a bug with the way arguments were called. It's fixed now. 

I did notice that your structures don't look very good. Here's [your structure for chr1](https://drive.google.com/file/d/1jvBAg1bQU8pZBMpoypn-NYnl9AkKKpMA/view?usp=sharing). Compare the [Rao structure for chr1](https://drive.google.com/file/d/1_iNZA510Y-r9R7Q4c9KajKhk392hIXFW/view?usp=sharing) for the same cell type and resolution. One reason could be lower coverage: your input file has less than half as many nonzero bins as the Rao file. There could also be an issue with normalization. To check if it's due to normalization or data quality, you could try using a raw (un-normalized) file as input. Raw files can generally produce okay structures, other than a few outliers. For example, here's the [raw Rao structure](https://drive.google.com/file/d/1xaqxrP4RW1vL-cyHqahhoul0oHVpg-iC/view?usp=sharing).

**Comment by hanfu-bios** [comment]
Thank you for the timely update! But I still have problems now. After I pulled the latest code and ran it on the data, I got the error message below:

`Low-resolution MDS complete
[21000000 22000000 23000000 24000000 25000000 29000000 30000000 40000000]
No handlers could be found for logger "pymp"
1`

Any idea why? Thanks!

**Comment by Lila14** [comment]
Sorry, that wasn't a very useful error message. I've updated the code to produce more useful messages. The issue was that there were empty rows in a matrix. This is because your input BED files had some lines with 0 counts, which is not allowed. I removed those lines when I tested your data (see attachment)
[K562_cleaned.tar.gz](https://github.com/seqcode/miniMDS/files/2207069/K562_cleaned.tar.gz)
.

**Comment by hanfu-bios** [comment]
Lila - thank you so much for your help! I can generate results from my data now. But I would like to replicate the results you sent me from Rao’s data. Can you show me where I can download Rao’s data or simply send me the data input if possible?

Many thanks!

**Comment by Lila14** [comment]
The script get_gm12878.sh will download and normalize the Rao GM12878 intrachromosomal data for a given chromosome and resolution.
For example, to get chr22 100-kb resolution:
./get_gm12878.sh 100000 22

To get all chromosomes at 100-kb resolution:
./get_gm12878.sh 100000 0

get_gm12878_inter.sh downloads and normalizes interchromosomal data for all chromosomes at a given resolution. For example:
./get_gm12878_inter.sh 100000
